apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/www/html"
