#!/bin/bash
source ${HOME}/bin/library
if [ ${#} -eq 0 ]; then
   p=`cat POD_CT` && m=`cat MSTR_CT` && i=0 && m=0 && pods= && master=
   while [ $i -lt ${p} ]; do
      i=`expr ${i} + 1` && pods="${pods} node${i}"
   done
   boxes="master ${pods}"
   echo -n "Destroying env(s) " && blue "${PWD##*/}" && echo "  for ${boxes}"
   for i in 3 2 1; do echo -e "\t\tin $i"; sleep 1; done
   CMD="vagrant destroy ${boxes} -f" && inf ${CMD} && time ${CMD}
else

if [ ${#} -gt 0 ]; then vagrant destroy ${@} -f; else echo " Usage: Need argument(s) for vagrant destroy"; fi

fi
