#!/bin/bash

for i in "$@"
do
case $i in
        -p=*|-provision-with=*)
        PROVISIONWITH="--provision-with ${i#*=}"
        shift # past argument=value
        ;;
esac
done

echo "Executing: vagrant provision ${@} ${PROVISIONWITH}"
if [ ${#} -gt 0 ];
 then time vagrant provision ${@} ${PROVISIONWITH} && vagrant provision ${@} --provision-with SyncTest;
 else if [[ ! -z ${PROVISIONWITH} ]]; then vagrant provision ${PROVISIONWITH} && vagrant provision ${@} --provision-with SyncTest; fi;
 fi
