#!/bin/bash

for i in "$@"
do
case $i in
        -p=*|-provision-with=*)
        PROVISIONWITH="--provision-with ${i#*=}"
        shift # past argument=value
        ;;
esac
done

echo "Executing: vagrant up ${@} ${PROVISIONWITH}"
if [ ${#} -gt 0 ]; then time vagrant up ${@} ${PROVISIONWITH}; else echo " Usage: up [-p=PROV1,PROV2...] BOX1 [BOX2]..."; fi
