#!/bin/bash

for i in "$@"
do
case $i in
        -p=*|-provision-with=*)
        PROVISIONWITH="--provision-with ${i#*=}"
        shift # past argument=value
        ;;
esac
done

echo -n "Executing: vagrant up ${@}"; if [[ ! -z ${PROVISIONWITH} ]]; then echo -n " then provisioning with ${PROVISIONWITH} "; fi; echo
if [ ${#} -gt 0 ]; then time vagrant up ${@} && if [[ ! -z ${PROVISIONWITH} ]]; then vagrant provision ${@} ${PROVISIONWITH}; fi; else echo -e " Usage: up [-p=PROV1,PROV2...] BOX1 [BOX2]...\nThis runs vagrant up, then optional provision afterwards"; fi
