#!/bin/bash

# k8s-cluster

ln -fsn ../empty.sh ./empty.sh
ln -fsn ./empty.sh ./master.sh
ln -fsn ./empty.sh ./node.sh
ln -fsn ./empty.sh ./controller.sh
ln -fsn ../rootkey.sh ./rootkey.sh
ln -fsn ../vagrantkey.sh ./vagrantkey.sh
ln -fsn ../root_key.sh ./root_key.sh
ln -fsn ../vagrant_key.sh ./vagrant_key.sh
ln -fsn ubuntu.k8s.sh ./simple.sh
ln -fsn ../box.hosts_sync.sh ./sync.hosts.sh
ln -fsn ../ubuntu.commands.sudo.sh ./ubuntu.commands.sudo.sh
ln -fsn ../ubuntu.k8s.sh ./ubuntu.k8s.sh

if [ ! -d ./_shared_assets ]; then mkdir ./_shared_assets; fi


touch POD_CT
touch MSTR_CT
touch CTLR_CT
