# -*- mode: ruby -*-
# vi: set ft=ruby :

PURPOSE = "bionic64"
LIFECYCLE = "dev"
DOMAIN = "anytown.usa"

IMAGE = "ubuntu/bionic64"
PROVIDER = "virtualbox"
ROOT_KEY = "root_key.sh"

MASTER = "master"
MASTER_SCRIPT = "master.sh"
HOSTNAME_MASTER = "#{MASTER}.#{LIFECYCLE}.#{DOMAIN}"
VM_NAME_MASTER = "#{PURPOSE}_#{LIFECYCLE}_#{MASTER}"

NODE_COUNT = 0 ### CHANGING HERE HAS NO EFFECT ###
NODE = "node"
NODE_SCRIPT = "master.sh"
HOSTNAME_NODE = "#{NODE}.#{LIFECYCLE}.#{DOMAIN}"
VM_NAME_NODE = "#{PURPOSE}_#{LIFECYCLE}_#{NODE}"
# md5<<<`date -j -f "%a %b %d %T %Z %Y" "\`date\`" "+%s"`
# ssh-keygen -t rsa -f /Users/brandonindia/.ssh/vagrant/id_rsa.`date -j -f "%a %b %d %T %Z %Y" "\`date\`" "+%s"` -b 4096 -q -N ""

### GENERATE UNIQUE KEYS HERE ###
$GENKEY = <<EOF
sudo date > /etc/vagrant_provisioned_at
ssh-keygen -t rsa -b 4096 -f "/root/.ssh/vagrant_provisioning_id_rsa.`date +%s`" -q -N ""
EOF
#$NODE_SCRIPT = <<SCRIPT

#SCRIPT
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

### NO DEFAULT ###
   #config.vm.box = IMAGE

### MASTER ###
   config.vm.define "#{MASTER}" do |subconfig|
      subconfig.vm.box = "#{IMAGE}"
      subconfig.vm.hostname = "#{MASTER}.#{PURPOSE}.#{LIFECYCLE}.#{DOMAIN}"
      subconfig.vm.provider "#{PROVIDER}" do |v|
         v.name = "#{VM_NAME_MASTER}"
         #v.memory = 2048
      end
      subconfig.ssh.insert_key = true
      #subconfig.vm.provision "shell", path: "#{MASTER_SCRIPT}"
      subconfig.vm.provision "shell", path: "#{ROOT_KEY}"
      subconfig.vm.provision "shell", inline: $GENKEY

      #PORT = 2200
      #subconfig.vm.network "forwarded_port", guest: 22, host: PORT, id: "ssh", auto_correct: false
      subconfig.vm.network "private_network", ip: "10.250.0.101", virtualbox__intnet: "anytownusa"
   end
### MASTER ###

### NODES ###
   NODE_COUNT = 1
   (1..NODE_COUNT).each do |i|
      config.vm.define "#{NODE}#{i}" do |subconfig|
         subconfig.vm.box = "#{IMAGE}"
         subconfig.vm.hostname = "#{NODE}#{i}.#{PURPOSE}.#{LIFECYCLE}.#{DOMAIN}"
         subconfig.vm.provider "#{PROVIDER}" do |v|
           v.name = "#{VM_NAME_NODE}#{i}"
           #v.memory = 2048
         end
         subconfig.ssh.insert_key = true
         #subconfig.vm.provision "shell", path: "#{NODE_SCRIPT}"
         subconfig.vm.provision "shell", path: "#{ROOT_KEY}"
         subconfig.vm.provision "shell", inline: $GENKEY

         #PORT = 2200 + i
         #subconfig.vm.network "forwarded_port", guest: 22, host: PORT, id: "ssh", auto_correct: false
         subconfig.vm.network "private_network", ip: "10.250.0.#{i}", virtualbox__intnet: "anytownusa"
      end
   end
### NODES ###


### END ###
end
