#!/bin/bash

# k8s-cluster

#rm -rf ./empty.sh master.sh node.sh controller.sh ./root_key.sh ./simple.sh ./sync.hosts.sh ./ubuntu.commands.sudo.sh ./ubuntu.k8s.sh ./vagrant_key.sh

ln -fsn ../empty.sh ./empty.sh
ln -fsn empty.sh master.sh
ln -fsn empty.sh node.sh
ln -fsn empty.sh controller.sh
ln -fsn ../root_key.sh ./root_key.sh
ln -fsn ubuntu.k8s.sh ./simple.sh
ln -fsn ../box.hosts_sync.sh ./sync.hosts.sh
ln -fsn ../ubuntu.commands.sudo.sh ./ubuntu.commands.sudo.sh
ln -fsn ../ubuntu.k8s.sh ./ubuntu.k8s.sh
ln -fsn ../vagrant_key.sh ./vagrant_key.sh

base=k8s-cluster
# RECURSIVELY LINKS ASSET FILES
dir=_shared_assets && target=./${dir} && src=../${base}/${dir}
if [ ! -d ${target} ]; then mkdir ${target}; fi
for f in $(ls -1 ${src}/); do if [ ! -d ${src}/${f} ]; then ln -fn ${src}/${f} ./${target}/${f}; fi; done

dir=_shared_assets/techcraz && target=./${dir} && src=../${base}/${dir}
if [ ! -d ${target} ]; then mkdir ${target}; fi
for f in $(ls -1 ${src}/); do if [ ! -d ${src}/${f} ]; then ln -fn ${src}/${f} ./${target}/${f}; fi; done

echo 0 > CTLR_CT
echo 1 > MSTR_CT
echo 1 > POD_CT
