kind: Service
apiVersion: v1
metadata:
  name: wordpress-service-np
  labels:
    name: wordpress
spec:
  type: NodePort
  ports:
  - port: 32536
    nodePort: 31162
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: wordpress
